#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP
if [ "$1" ] && [ "$2" ]
then
    dig "$2"".""$1" | grep -A1 'ANSWER SECTION:' | tail -n 1| awk -v var="$2" '{ print "The subdomain " var " is a " $4 " record and points to " $5}'
else
    dig "www"".""$1" | grep -A1 'ANSWER SECTION:' | tail -n 1| awk -v var="www" '{ print "The subdomain " var " is a " $4 " record and points to " $5}'
    dig "lb-01"".""$1" |grep -a1 'ANSWER SECTION:' | tail -n 1| awk -v var="lb-01" '{ print "The subdomain " var " is a " $4 " record and points to " $5}'
    dig "web-01"".""$1" |grep -a1 'ANSWER SECTION:' | tail -n 1| awk -v var="web-01" '{ print "The subdomain " var " is a " $4 " record and points to " $5}'
    dig "web-02"".""$1" |grep -a1 'ANSWER SECTION:' | tail -n 1| awk -v var="web-02" '{ print "The subdomain " var " is a " $4 " record and points to " $5}'
fi
