#!/usr/bin/env bash
# Configure your Nginx server
sudo apt-get update -y
sudo apt-get install nginx -y
#sudo chmod -R 755 /var/www
sudo touch /var/www/html/index.html
echo "Holberton School" > index_m.html
sudo mv index.html /var/www/html/index.html
#sudo service nginx start
sudo sed -i '46 i\\trewrite ^\/redirect_me https://www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
