#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i "51i\ add_header X-Served-By: $HOSTNAME" ; /etc/nginx/sites-enabled/default;
sudo service nginx restart
