#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i "5li \\\t\tadd_header X-Served-By: $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
