#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*

echo "frontend http_front
        bind *:80
        mode http
        option forwardfor
        default_backend http_back

backend http_back
    balance roundrobin
    server 955-web-01 35.229.16.216:80 check
    server 955-web-02 34.73.228.13:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
