#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*

sudo service haproxy start
echo "frontend haproxynode
        bind *:80
mode http
default_backend backendnodes
backend backendnodes
 balance roundrobin
server 955-web-01 35.231.10.1:80 check
server 955-web-02 34.74.111.90:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
