#!/usr/bin/env bash
#Run Nginx as Nginx
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -su "nginx" service nginx restart
