#!/usr/bin/env bash
#Run Nginx as Nginx in less than 7 lines
sudo pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -su "nginx" service nginx restart
